# Generated by Django 4.2.4 on 2023-11-01 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField()),
                ('engine_model', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100)),
                ('number_plates', models.CharField(max_length=100)),
                ('altitude', models.FloatField()),
                ('date', models.DateTimeField()),
                ('gps_distance', models.FloatField()),
                ('gps_speed', models.FloatField()),
                ('ignition', models.BooleanField()),
                ('is_satellite_source', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('nearest_city_name', models.CharField(max_length=100)),
                ('nearest_city_distance', models.FloatField()),
                ('nearest_city_orientation', models.CharField(max_length=100)),
                ('nearest_city_reference', models.CharField(max_length=100)),
                ('orientation', models.FloatField()),
                ('orientation_label', models.CharField(max_length=100)),
                ('satellites', models.IntegerField()),
                ('serial_number', models.CharField(max_length=100)),
                ('sim_imei', models.CharField(max_length=100)),
                ('vehicle_brand', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('vehicle_year', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField()),
                ('event', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=100)),
                ('event_type_name', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtasks.devicedata')),
            ],
        ),
    ]
