# Generated by Django 4.2.4 on 2023-09-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_address', models.AutoField(primary_key=True, serialize=False)),
                ('address_supplier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id_driver', models.AutoField(primary_key=True, serialize=False)),
                ('name_driver', models.CharField(max_length=35)),
                ('celphone', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('e_mail', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IdConcept',
            fields=[
                ('id_concept', models.AutoField(primary_key=True, serialize=False)),
                ('name_concept', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id_month', models.AutoField(primary_key=True, serialize=False)),
                ('name_month', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id_origin', models.AutoField(primary_key=True, serialize=False)),
                ('name_origin', models.CharField(max_length=20)),
                ('state_origin', models.CharField(max_length=20)),
                ('min_time', models.TimeField()),
                ('max_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id_tipe', models.AutoField(primary_key=True, serialize=False)),
                ('name_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_suppler', models.AutoField(primary_key=True, serialize=False)),
                ('name_supplier', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id_trailer', models.AutoField(primary_key=True, serialize=False)),
                ('trailer_num', models.CharField(max_length=4)),
                ('plate', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('vin', models.CharField(max_length=25)),
                ('trademark', models.CharField(max_length=15)),
                ('assured', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id_truck', models.AutoField(primary_key=True, serialize=False)),
                ('truck_num', models.CharField(max_length=4)),
                ('plate', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('vin', models.CharField(max_length=25)),
                ('trademark', models.CharField(max_length=15)),
                ('assured', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='type_fact',
            fields=[
                ('id_typef', models.AutoField(primary_key=True, serialize=False)),
                ('type_namef', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='type_note',
            fields=[
                ('id_typen', models.AutoField(primary_key=True, serialize=False)),
                ('type_namen', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='Creacion')),
                ('lote', models.IntegerField(blank=True, db_column='Número de Lote', null=True)),
                ('week', models.CharField(blank=True, db_column='Semana', max_length=2, null=True)),
                ('weight', models.IntegerField(blank=True, db_column='Peso', null=True)),
                ('serv_date', models.DateField(blank=True, db_column='Fecha de Servicio', null=True)),
                ('meeting_place', models.CharField(blank=True, db_column='Lugar de Encuentro', max_length=50, null=True)),
                ('meeting_hour', models.TimeField(blank=True, db_column='Hora de Encuentro', null=True)),
                ('ranch_exit', models.DateTimeField(blank=True, db_column='Salida de Rancho', null=True)),
                ('kms_exit', models.IntegerField(blank=True, db_column='Kilómetros de Salida', null=True)),
                ('arrive_point', models.DateTimeField(blank=True, db_column='Punto de Llegada', null=True)),
                ('arrive_kms', models.IntegerField(blank=True, db_column='Kilómetros de Llegada a Cita', null=True)),
                ('arrive_supp', models.DateTimeField(blank=True, db_column='Legada al acopio', null=True)),
                ('arrive_kmssupp', models.IntegerField(blank=True, db_column='Kilómetros de Llegada al acopio', null=True)),
                ('cargo1_arrival', models.DateTimeField(blank=True, db_column='Llegada de Carga 1', null=True)),
                ('cargo1_kms', models.IntegerField(blank=True, db_column='Kilómetros de Carga 1', null=True)),
                ('cargo1_collected', models.IntegerField(blank=True, db_column='Carga 1 Recogida', null=True)),
                ('cargo1_fin', models.DateTimeField(blank=True, db_column='Finalización de Carga 1', null=True)),
                ('cargo1_coordinates', models.CharField(blank=True, db_column='Coordenadas 1', max_length=50, null=True)),
                ('cargo2_arrival', models.DateTimeField(blank=True, db_column='Llegada de Carga 2', null=True)),
                ('cargo2_kms', models.IntegerField(blank=True, db_column='Kilómetros de Carga 2', null=True)),
                ('cargo2_collected', models.IntegerField(blank=True, db_column='Carga 2 Recogida', null=True)),
                ('cargo2_fin', models.DateTimeField(blank=True, db_column='Finalización de Carga 2', null=True)),
                ('cargo2_coordinates', models.CharField(blank=True, db_column='Coordenadas 2', max_length=50, null=True)),
                ('cargo3_arrival', models.DateTimeField(blank=True, db_column='Llegada de Carga 3', null=True)),
                ('cargo3_kms', models.IntegerField(blank=True, db_column='Kilómetros de Carga 3', null=True)),
                ('cargo3_collected', models.IntegerField(blank=True, db_column='Carga 3 Recogida', null=True)),
                ('cargo3_fin', models.DateTimeField(blank=True, db_column='Finalización de Carga 3', null=True)),
                ('cargo3_coordinates', models.CharField(blank=True, db_column='Coordenadas 3', max_length=50, null=True)),
                ('exit_supplier', models.DateTimeField(blank=True, db_column='Salida de Proveedor', null=True)),
                ('exit_supplierkms', models.IntegerField(blank=True, db_column='Kilómetros salida Proveedor', null=True)),
                ('comentaries', models.TextField(blank=True, db_column='Comentarios', max_length=200, null=True)),
                ('ranch_arrive', models.DateTimeField(blank=True, db_column='Llegada a Rancho', null=True)),
                ('ranch_kms', models.IntegerField(blank=True, db_column='Kilómetros a Rancho', null=True)),
                ('total_collected', models.IntegerField(blank=True, db_column='Total Recogido', null=True)),
                ('total_kms', models.IntegerField(blank=True, db_column='Total de Kilómetros', null=True)),
                ('empty_kms', models.IntegerField(blank=True, db_column='Kilómetros Vacíos', null=True)),
                ('dead_kms', models.IntegerField(blank=True, db_column='Kilómetros Muertos', null=True)),
                ('lts_diesel', models.DecimalField(blank=True, db_column='Litros de Diesel', decimal_places=2, max_digits=5, null=True)),
                ('performance', models.DecimalField(blank=True, db_column='Rendimiento', decimal_places=2, max_digits=5, null=True)),
                ('urea', models.DecimalField(blank=True, db_column='Urea', decimal_places=2, max_digits=5, null=True)),
                ('stand', models.DecimalField(blank=True, db_column='Stand', decimal_places=2, max_digits=5, null=True)),
                ('iave', models.DecimalField(blank=True, db_column='IAVE', decimal_places=2, max_digits=5, null=True)),
                ('food', models.DecimalField(blank=True, db_column='Comida', decimal_places=2, max_digits=5, null=True)),
                ('dessinfections', models.DecimalField(blank=True, db_column='Desinfecciones', decimal_places=2, max_digits=5, null=True)),
                ('fixes', models.DecimalField(blank=True, db_column='Reparaciones', decimal_places=2, max_digits=5, null=True)),
                ('parts', models.DecimalField(blank=True, db_column='Partes', decimal_places=2, max_digits=5, null=True)),
                ('tires', models.DecimalField(blank=True, db_column='Llantas', decimal_places=2, max_digits=5, null=True)),
                ('pension', models.DecimalField(blank=True, db_column='Pensión', decimal_places=2, max_digits=5, null=True)),
                ('federal', models.DecimalField(blank=True, db_column='Federal', decimal_places=2, max_digits=5, null=True)),
                ('fact_cp', models.CharField(blank=True, db_column='Código Postal de Factura', max_length=8, null=True)),
                ('date_fact', models.DateTimeField(blank=True, db_column='Fecha de Factura', null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Monto', decimal_places=2, max_digits=5, null=True)),
                ('unit_price', models.DecimalField(blank=True, db_column='Precio Unitario', decimal_places=2, max_digits=5, null=True)),
                ('amount_note', models.DecimalField(blank=True, db_column='Monto de Nota', decimal_places=2, max_digits=5, null=True)),
                ('cargo1_site', models.ForeignKey(blank=True, db_column='Sitio de Carga 1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_cargo1', related_query_name='trip_cargo1', to='services.address')),
                ('cargo2_site', models.ForeignKey(blank=True, db_column='Sitio de Carga 2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_cargo2', related_query_name='trip_cargo2', to='services.address')),
                ('cargo3_site', models.ForeignKey(blank=True, db_column='Sitio de Carga 3', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_cargo3', related_query_name='trip_cargo3', to='services.address')),
                ('driver', models.ForeignKey(blank=True, db_column='Conductor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.driver')),
                ('month', models.ForeignKey(blank=True, db_column='Mes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.month')),
                ('oigin', models.ForeignKey(blank=True, db_column='Origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.origin')),
                ('supplier', models.ForeignKey(blank=True, db_column='Proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.supplier')),
                ('trailer', models.ForeignKey(blank=True, db_column='Remolque', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.trailer')),
                ('trailer_plates', models.ForeignKey(blank=True, db_column='Placas de Remolque', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignations_with_trailer_plates', to='services.trailer')),
                ('truck', models.ForeignKey(blank=True, db_column='Camión', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.truck')),
                ('truck_plates', models.ForeignKey(blank=True, db_column='Placas de Camión', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignations_with_truck_plates', to='services.truck')),
                ('type_fact', models.ForeignKey(blank=True, db_column='Tipo de Factura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.type_fact')),
                ('type_note', models.ForeignKey(blank=True, db_column='Tipo de Nota', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.type_note')),
                ('type_service', models.ForeignKey(blank=True, db_column='Tipo de Servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='MonthExpenses',
            fields=[
                ('id_expenses', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expense_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proportional_trip', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proportional_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.month')),
                ('name_conceptt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.idconcept')),
            ],
        ),
    ]
