# Generated by Django 4.2.4 on 2023-10-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id_route', models.AutoField(primary_key=True, serialize=False)),
                ('name_route', models.CharField(max_length=150)),
                ('desc_route', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_route', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon_route', models.DecimalField(decimal_places=6, max_digits=9)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.route')),
            ],
        ),
    ]
