# Generated by Django 4.2.4 on 2023-10-23 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_route_routepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='route',
            field=models.ForeignKey(blank=True, db_column='Ruta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.route'),
        ),
    ]
