# Generated by Django 4.2.4 on 2023-10-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mci',
            fields=[
                ('id_mci', models.AutoField(primary_key=True, serialize=False)),
                ('mci_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mci_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id_part', models.AutoField(primary_key=True, serialize=False)),
                ('week_num', models.IntegerField(blank=True, null=True)),
                ('name_part', models.CharField(blank=True, max_length=30, null=True)),
                ('cal_day1', models.IntegerField(blank=True, null=True)),
                ('cal_day2', models.IntegerField(blank=True, null=True)),
                ('cal_day3', models.IntegerField(blank=True, null=True)),
                ('cal_day4', models.IntegerField(blank=True, null=True)),
                ('cal_day5', models.IntegerField(blank=True, null=True)),
                ('cal_day6', models.IntegerField(blank=True, null=True)),
                ('cal_day7', models.IntegerField(blank=True, null=True)),
                ('prom_wek', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mdp',
            fields=[
                ('id_mdp', models.AutoField(primary_key=True, serialize=False)),
                ('mdp_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mdp_active', models.BooleanField(blank=True, default=None, null=True)),
                ('id_mci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='boardmci.mci')),
            ],
        ),
    ]
