# Generated by Django 4.2.4 on 2023-09-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionStatus',
            fields=[
                ('id_condition', models.AutoField(primary_key=True, serialize=False)),
                ('condition_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PortSupplier',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('port_supplier', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('capacity', models.CharField(max_length=10, null=True)),
                ('serv_date', models.DateField(blank=True, null=True)),
                ('ranch_exitd', models.DateTimeField(blank=True, null=True)),
                ('ubi_exit', models.CharField(blank=True, max_length=50, null=True)),
                ('kms_exit', models.IntegerField(blank=True, null=True)),
                ('calt_date', models.DateTimeField(blank=True, null=True)),
                ('ubi_calt', models.CharField(blank=True, max_length=50, null=True)),
                ('kms_calt', models.IntegerField(blank=True, null=True)),
                ('date_arrives', models.DateTimeField(blank=True, null=True)),
                ('ubi_arrives', models.CharField(blank=True, max_length=50, null=True)),
                ('kms_arrives', models.IntegerField(blank=True, null=True)),
                ('initc_date', models.DateTimeField(blank=True, null=True)),
                ('ubi_initchar', models.CharField(blank=True, max_length=50, null=True)),
                ('kms_initchar', models.IntegerField(blank=True, null=True)),
                ('endchar_date', models.DateTimeField(blank=True, null=True)),
                ('ubi_endchar', models.CharField(blank=True, max_length=50, null=True)),
                ('kms_endchar', models.IntegerField(blank=True, null=True)),
                ('fiscal_date', models.DateTimeField(blank=True, null=True)),
                ('ubi_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('kms_fiscal', models.IntegerField(blank=True, null=True)),
                ('exitport_date', models.DateTimeField(blank=True, null=True)),
                ('ubi_exitport', models.CharField(blank=True, max_length=50, null=True)),
                ('kms_exitport', models.IntegerField(blank=True, null=True)),
                ('arriver_date', models.DateTimeField(blank=True, null=True)),
                ('ubi_arriver', models.CharField(blank=True, max_length=50, null=True)),
                ('kms_arriver', models.IntegerField(blank=True, null=True)),
                ('initdown_date', models.DateTimeField(blank=True, null=True)),
                ('ubi_initdown', models.CharField(blank=True, max_length=50, null=True)),
                ('kms_initdown', models.IntegerField(blank=True, null=True)),
                ('enddown_date', models.DateTimeField(blank=True, null=True)),
                ('ubi_enddown', models.CharField(blank=True, max_length=50, null=True)),
                ('kms_enddown', models.IntegerField(blank=True, null=True)),
                ('emptyranch_date', models.DateTimeField(blank=True, null=True)),
                ('ubi_emptyranh', models.CharField(blank=True, max_length=50, null=True)),
                ('kms_emptyranch', models.IntegerField(blank=True, null=True)),
                ('total_kms', models.IntegerField(blank=True, null=True)),
                ('empty_kms', models.IntegerField(blank=True, null=True)),
                ('dead_kms', models.IntegerField(blank=True, null=True)),
                ('lts_diesel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('performance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('urea', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fact_cp', models.CharField(blank=True, max_length=8, null=True)),
                ('date_fact', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condition_arriver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='erriver_condition', to='supplies.conditionstatus')),
                ('condition_arrives', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrives_condition', to='supplies.conditionstatus')),
                ('condition_calt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calt_condition', to='supplies.conditionstatus')),
                ('condition_emptyranch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empty_condition', to='supplies.conditionstatus')),
                ('condition_endchar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_condition', to='supplies.conditionstatus')),
                ('condition_enddown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='endd_condition', to='supplies.conditionstatus')),
                ('condition_exit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_condition', to='supplies.conditionstatus')),
                ('condition_exitport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exitport_condition', to='supplies.conditionstatus')),
                ('condition_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fiscal_condition', to='supplies.conditionstatus')),
                ('condition_initchar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='init_condition', to='supplies.conditionstatus')),
                ('condition_initdown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='initd_condition', to='supplies.conditionstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id_turn', models.AutoField(primary_key=True, serialize=False)),
                ('turn', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSupplie',
            fields=[
                ('id_supplie', models.AutoField(primary_key=True, serialize=False)),
                ('name_supplie', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id_day', models.AutoField(primary_key=True, serialize=False)),
                ('name_day', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SupplieStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_status', models.DateTimeField(auto_now_add=True)),
                ('time_consult', models.DateTimeField(blank=True, null=True)),
                ('time_dif', models.DurationField(blank=True, null=True)),
                ('kms', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.conditionstatus')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.driver')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.supplies')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.status')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.portsupplier')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.turn')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.truck')),
            ],
        ),
        migrations.AddField(
            model_name='supplies',
            name='day_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.weekdays'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.driver'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.month'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='port_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.portsupplier'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='status_arrive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arriving_supplier', to='supplies.status'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='status_arriver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arriving_ranch', to='supplies.status'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='status_calt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arriving_calt', to='supplies.status'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='status_emptyranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empty_ranch', to='supplies.status'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='status_endchar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_char', to='supplies.status'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='status_enddown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_down', to='supplies.status'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='status_exit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exit_ranch', to='supplies.status'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='status_exitport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exit_port', to='supplies.status'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='status_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fiscal', to='supplies.status'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='status_initchar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='init_char', to='supplies.status'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='status_initdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='init_down', to='supplies.status'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.trailer'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='trailer_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignations_with_trailer_plate', to='services.trailer'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.truck'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='truck_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignations_with_truck_plate', to='services.truck'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='turns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.turn'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='type_supplie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.typesupplie'),
        ),
    ]
